server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://82.156.194.208:3306/work_platform?serverTimezone=GMT%2B8
    username: root
    password: Justmyself957!
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 120000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    port: 6379
    password: Justmyself957!
    host: 82.156.194.208
    database: 1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000
      shutdown-timeout: 100

  rabbitmq:
    host: 82.156.194.208
    port: 5672
    username: mercer
    password: Justmyself957!


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30